### ISSUE TITLE
Data wide - population

### ISSUE THREAD

**Issue by luisotavio88** [samcarlos/covid19_trade#1]
Hi Samuel,

Thank you for sharing. I am trying to reproduce your code to show to my students. But, I got stucked at this line:

data_wide_3[,'population'] = as.numeric(data_wide_3[,'population'])

I downloaded the data you used from https://oec.world/en/resources/data/ but I could not find data_wide_3. Or even when I consider data_wide_2 there is no variable "population".

Am I missing something?

Thank you.

Luis

**Comment by samcarlos** [comment]
Hey Luis, 

I updated code to show missing part. Data for population can be found here #population found here https://data.worldbank.org/indicator/SP.POP.TOTL. 

Thanks for pointing that out and sorry for inconvenience. 

Sam
